github: ponfertato # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
#liberapay: potatoenergy # Replace with a single Liberapay username
custom: ['https://vtb.paymo.ru/collect-money/qr/?transaction=44b97c8b-1e77-43e6-b30a-de729462c934', 'https://yoomoney.ru/to/410011985481953'] # Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
