---
services:
  hugo:
    command: server --appendPort=false --baseURL=http://localhost:1313/ --buildDrafts --disableFastRender
    container_name: hugo
    image: hugomods/hugo:base
    ports:
      - 1313:1313
    restart: unless-stopped
    volumes:
      - .:/src