---
ignoreLogs: ['warning-partial-superfluous-prefix']
baseURL: https://potatoenergy.ru/
buildDrafts: true
buildExpired: false
buildFuture: false
copyright: © 2023-2025 **[Potato Energy Team](https://potatoenergy.ru/)**
defaultContentLanguage: ru
disableKinds: ['404']
enableEmoji: true
enableInlineShortcodes: true
enableRobotsTXT: true
languages:
  en:
    languageName: ':uk:'
    menu:
      main:
        - name: Status
          params:
            external: true
          url: https://status.potatoenergy.ru/
          weight: 90
        - name: Grafana
          params:
            external: true
          url: https://potatoenergy.ru/grafana/
        - name: AI
          params:
            external: true
          url: https://chat.potatoenergy.ru/
          weight: 5
        - name: Nextcloud
          params:
            external: true
          url: https://cloud.potatoenergy.ru/
        - name: Mastodon
          params:
            external: true
          url: https://social.potatoenergy.ru/
        - name: Search
          url: search
          weight: 1
        - name: Blog
          url: blog
          weight: 3
        - name: Login
          params:
            external: true
          url: https://auth.potatoenergy.ru/
          weight: 99
    params:
      profileMode:
        buttons:
          - name: Services
            url: services
          - name: News
            url: news
          - name: Team
            url: team
        enabled: true
        imageTitle: Potato Energy Logo
        imageUrl: images/icon.png
        subtitle: >  
          🥔 **Potato Energy** - where the tubers of tradition sprout into IT innovation

          *“Because even space technology starts with Earth potatoes.”*
          
          (🕒 Daily from 08:00 to 00:00)
        title: >
          Potato Energy
      title: English
    taxonomies:
      category: categories
      series: series
      tag: tags
    weight: 1
  ru:
    languageName: ':ru:'
    menu:
      main:
        - name: Статус
          params:
            external: true
          url: https://status.potatoenergy.ru/
          weight: 90
        - name: Grafana
          params:
            external: true
          url: https://potatoenergy.ru/grafana/
        - name: ИИ
          params:
            external: true
          url: https://chat.potatoenergy.ru/
          weight: 5
        - name: Nextcloud
          params:
            external: true
          url: https://cloud.potatoenergy.ru/
        - name: Mastodon
          params:
            external: true
          url: https://social.potatoenergy.ru/
        - name: Поиск
          url: search
          weight: 1
        - name: Блог
          url: blog
          weight: 3
        - name: Вход
          params:
            external: true
          url: https://auth.potatoenergy.ru/
          weight: 99
    params:
      profileMode:
        buttons:
          - name: Сервисы
            url: services
          - name: Новости
            url: news
          - name: Команда
            url: team
        enabled: true
        imageTitle: Potato Energy Logo
        imageUrl: images/icon.png
        subtitle: >  
          🥔 **Potato Energy** — где клубни традиций прорастают в IT-инновации  

          *“Потому что даже космические технологии начинаются с земного картофеля”*  
          
          (🕒 Ежедневно с 08:00 по 00:00)
        title: >
          Картофельная Энергия
      title: Русский
    taxonomies:
      category: categories
      series: series
      tag: tags
    weight: 2
mainsections: ["posts", "news"]
markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    noClasses: false
minify:
  disableXML: true
outputs:
  home:
    - HTML
    - RSS
    - JSON
pagination:
  pagerSize: 5
params:
  EnableImageZoom: true
  EnableInstantClick: true
  ShowAllPagesInArchive: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowPageNums: true
  ShowPostNavLinks: true
  ShowReadingTime: true
  ShowRssButtonInSectionTermList: true
  ShowShareButtons: false
  ShowToc: true
  ShowWordCount: true
  TocOpen: true
  TocSide: right
  social:
    fediverse_creator: "@ponfertato@potatoenergy.ru"
  analytics:
    yandex:
      SiteVerificationTag: '94077410'
  assets:
    apple_touch_icon: apple-touch-icon.png
    disableHLJS: true
    favicon: favicon.ico
    favicon16x16: favicon-16x16.png
    favicon32x32: favicon-32x32.png
  author: ["Potato Energy"]
  commentSystems:
    remark42:
      components: ["embed", "last-comments"]
      host: https://potatoenergy.ru/remark42
      locale: ru
      max_shown_comments: 15
      no_footer: false
      show_email_subscription: false
      show_rss_subscription: true
      simple_view: true
      site_id: potatoenergy
      theme: dark
  comments: true
  dateFormat: 02 Jan 2006
  defaultTheme: auto
  description: Potato Energy - Откройте для мира потенциал картофеля вместе с нами!
  disableSpecial1stPost: false
  disableThemeToggle: false
  displayFullLangName: true
  env: production
  fuseOpts:
    distance: 1000
    isCaseSensitive: false
    keys: ["title", "permalink", "summary", "content"]
    location: 0
    minMatchCharLength: 0
    shouldSort: true
    threshold: 0.4
  images: ["images/papermod-cover.png"]
  logo:
    icon: images/icon.png
    iconHeight: 35
    text: Potato Energy
  socialIcons:
    - name: discord
      title: Join us on Discord
      url: https://discord.gg/GH4PbUfzXR
    - name: telegram
      title: Join us on Telegram
      url: https://t.me/potatoenergy
    - name: steam
      title: Join us on Steam
      url: https://steamcommunity.com/groups/potatoenergy
    - name: matrix
      title: Join us on Matrix
      url: https://matrix.to/#/#potatoenergy:matrix.org
    - name: codeberg
      title: View Source on Codeberg
      url: https://codeberg.org/potatoenergy
    - name: github
      title: View Source on Github
      url: https://github.com/potatoenergy
    - name: email
      params:
        external: true
      title: Mail
      url: mailto:mail@potatoenergy.ru
    - name: rss
      title: RSS
      url: index.xml
  useCustomAnalytics: false
pygmentsUseClasses: true
theme: ["PaperMod"]
title: Potato Energy